### ISSUE TITLE
FeatureRequest: Model for dynamically referencing icons

### ISSUE THREAD

**Issue by userings** [iconify-design/iconify-react#17]
What is the cleanest way to dynamically include an icon in a React component? eg when an icon name is passed as a prop to the component and the component needs to display the icon. 

The structure of the packages do not lend themselves to ```import IconSet from '@iconify/icons-[set]'``` and use ```IconSet[iconname]```

**Comment by cyberalien** [comment]
So you want to pass a name instead of object, so you could reference that name in multiple files, making it easier to change icon for entire project?

**Comment by userings** [comment]
An API is called which responds with a set of names, most of which will have a related icon in an icon set. 

These names are passed to a component and the component should render the related icon. 

How does the icon object in node_modules, get passed to the component?

**Comment by cyberalien** [comment]
What you have described is behaviour of SVG framework. This React component is completely different. It does not use API.

So what you are looking for is React component that is similar to SVG framework that would use icon names and retrieve icon data from API?

**Comment by userings** [comment]
Apologies @cyberalien. I can see that this is out of scope of this module. I'll close the issue.
I can see that one possible solution to my problem would be to update the standard so that all iconify icon-set packages contain an index which exports all icons in the set. Given the focus around only loading the required icons that looks unlikely.

**Comment by cyberalien** [comment]
Its not out of scope though :)

I am working on Iconify version 2 right now. It is modular package that shares source with SVG framework, so it would be quite easy to implement React component with API. If you do want React component with API support, I can make one.

**Comment by userings** [comment]
That would be great!

**Comment by cyberalien** [comment]
Sorry for delay.

First version of React component with API support is available as NPM package `@iconify/react-with-api`

Source repository is here: https://github.com/iconify/iconify/tree/dev/packages/react-with-api
There is also demo package in same repository.

Differences from `@iconify/react`:
- You can reference icons by name: `<Icon icon="mdi-home" />`
- Exposes additional functions that are identical to SVG framework, which give you control over API stuff.

Additional functions:

`enableCache(storage: IconifyCacheType, value: boolean)`

Icons retrieved from API are cached in `sessionStorage`, this function can be used to enable/disable storage. By default, `sessionStorage` is enabled, `localStorage` is disabled.

```js
import { enableCache } from '@iconify/react-with-api`;

enableCache('session', false); // Disable sessionStorage
```

`loadIcons(icons: (IconifyIconName | string)[], 	callback?: IconifyIconLoaderCallback): IconifyIconLoaderAbort`

This function loads icons from API. If you know that some icons will be used conditionally at some point, I recommend preloading them using this function. This way when icon is needed, it will already be loaded from API. Also because script loads icons that are requested within same tick from API in bulk, using this function will make sure icons are retrieved at the same time, making it more efficient.

First parameter is array of icon names. Second parameter is an optional callback to call when icons have been loaded. Function returns function that aborts loading, so it can be used to cancel callback, which is useful to control dynamic loading within lifespan of component.

```js
import { loadIcons } from '@iconify/react-with-api';

loadIcons(['mdi:home', 'mdi:account'], () => {
    console.log('Few MDI icons have been loaded!');
});
```

There are also bunch of other useful functions, such as `iconExists` that checks if icon has been loaded, `addAPIProvider` to add custom API. I'll write full documentation for it this or next week.

**Comment by cyberalien** [comment]
Forgot to mention: unlike SVG framework that uses simple JSONP to retrieve data from API, React component uses XMLHttpRequest. This is experimental thing. I'll be testing how it works.

If you want to revert to JSONP behaviour, replace this line in `src/icon.ts`:
```js
import { getAPIModule } from '@iconify/core/lib/api/modules/axios';
```
with
```
import { getAPIModule } from '@iconify/core/lib/api/modules/jsonp';
```
and rebuild package.

To rebuild package first in root directory run `npm install` and `npm run bootstrap` to install all dependencies and create links between packages, then in `packages/react-with-api` run `npm run build` to build it.
