### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by fugaku** [iconify-design/iconify-react#19]
Hi, I'm using nextJS version 10
@iconify/react version 1.1.3
@iconify-icons/fa-solid version 1.1.0

I'm using iconify with typescript with below sample code
```tsx
import React from 'react';
import { Icon } from '@iconify/react';
import user from '@iconify-icons/fa-solid/user';

const Sidebar: React.FC = () => {
    return (
        <div>
            <Icon icon={user} />
        </div>
    );
};

export default Sidebar;
```

I have this error when nextJS compiles

`SyntaxError: Unexpected token 'export'`
`external%20%22@iconify-icons\fa-solid\user%22 (1:0) @ Object.@iconify-icons/fa-solid/user`
`module.exports = require("@iconify-icons/fa-solid/user");`

Any idea what I'm doing wrong ?

**Comment by cyberalien** [comment]
Those are ES modules. Looks like NextJS can only work with CommonJS.

Change package from `@iconify-icons/fa-solid` to `@iconify/icons-fa-solid`. It is identical, except that it uses CommonJS modules.

Why are there 2 versions of those modules? Because more modern bundling tools switch to ES modules and some even throw warnings when using CommonJS.

**Comment by italodeandra** [comment]
Hi @cyberalien,

Perhaps this could be added on the main documentation (close to the installation guide).

**Comment by cyberalien** [comment]
Added.

This repository has older version, which uses CommonJS modules in code examples, so no need to change anything here. 

New version in https://github.com/iconify/iconify/tree/master/packages/react uses ES modules in code examples. I've updated readme for that package.
