### ISSUE TITLE
Add flag-icon-css into core.

### ISSUE THREAD

**Issue by KhalilMohammad** [iconify-design/iconify-react#2]
I love the library.
I am here to suggest to add this [flag-icon-css](https://github.com/lipis/flag-icon-css)

**Comment by cyberalien** [comment]
That set looks good. I'll add it. Thanks for finding it.

**Comment by cyberalien** [comment]
Unfortunately this will have to wait.

Several icons in that set use text, which is not acceptable because it makes icon look different in different operating systems. Icons should include only vector shapes.

I tried to convert that text into shapes, but Sketch that I'm using to fix icons has bug with importing those icons, so they don't look the same as in browsers. That means I can't fix those icons by myself.

This icons set will have to wait until either author replaces text with shapes or Sketch team fixes SVG import bug.

**Comment by cyberalien** [comment]
Opened issue at flag-icons-css repository, hoping author would fix icons: https://github.com/lipis/flag-icon-css/issues/539

**Comment by cyberalien** [comment]
That project seems to be abandoned. I'll close this for now, though I'm subscribed to issue at flag-icons-css repository so if something changes I'll add flag icons to Iconify.

There are other options for flag with Iconify:
Twitter Emoji has flag emojis: https://iconify.design/icon-sets/twemoji/ (click "Flags" category)
EmojiOne has flag emojis: https://iconify.design/icon-sets/emojione/ (click "Flags" category)
EmojiOne 1 with different layout: https://iconify.design/icon-sets/emojione-v1/ (click "Flags" category)
