### ISSUE TITLE
Trying to load some icons in a react typescript app

### ISSUE THREAD

**Issue by peterennis** [iconify-design/iconify-react#8]
I used `npm install` for iconify and some icon sets, then tried to follow the guide
for webpack apps but get stuck with the import and referencing.

![Capture633](https://user-images.githubusercontent.com/140737/61348040-0fd5e880-a814-11e9-8353-cff05e9f8dd5.png)

Is there a working sample to review?

**Comment by cyberalien** [comment]
You don't need to import @iconify/iconify. @iconify/react is independent package, it bundles icons instead of using Iconify script.

Looking at highlights, I guess you didn't install @iconify/icons-mdi-light and @iconify/icons-twemoji. You do need to install each icons set you want to use by running something like `npm install @iconify/icons-mdi-light @iconify/icons-twemoji --save-dev`

**Comment by peterennis** [comment]
Fixed in this commit: https://github.com/peterennis/aeicons-react/commit/62d26576c643ed12b790a267c9e0170fe6571d36

Gif Demo: https://github.com/peterennis/aeicons-react
