### ISSUE TITLE
Parsing error: '=' expected

### ISSUE THREAD

**Issue by peterennis** [iconify-design/iconify-react#9]
![Capture634](https://user-images.githubusercontent.com/140737/61428752-6278d880-a8d8-11e9-96cc-295035db295b.png)

This is caused by the icon name chosen:

![Capture635](https://user-images.githubusercontent.com/140737/61428804-9d7b0c00-a8d8-11e9-8611-4edcf1570a90.png)

```
import { Icon, InlineIcon } from "@iconify/react";
import trophy from "@iconify/icons-mdi-light/trophy";
import airplane-arrival from "@iconify/icons-twemoji/airplane-arrival";
```

I am using a standard create react app for typescript

`npx create-react-app my-app --typescript`

It appears to be some sort of linting issue that will block loading of icons with dashes
in the name.

Test repo: https://github.com/peterennis/aeicons-react

**Comment by cyberalien** [comment]
That's correct error. You can name variable whatever you want, variables with dash are invalid.

That's why when you view such icon on Iconify website, it suggests to use different variable name: https://iconify.design/icon-sets/twemoji/airplane-arrival.html (click "React" tab):
```typescript
import airplaneArrival from '@iconify/icons-twemoji/airplane-arrival';
```

You can use any name for import. It imports default export, not named export:
```typescript
import notABoat from '@iconify/icons-twemoji/airplane-arrival';
```
